name: 'Compile Chrome Extension'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Extract Version'
        id: get_version
        run: |
          VERSION=$(jq -r '.version' src/main/chrome/manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 'Print Version'
        run: |
          echo "Extracted version: $VERSION"

      - name: 'Compile and Zip'
        run: |
          mkdir -p dist
          zip -r dist/Osprey-$VERSION-chrome.zip src/main/chrome

      - name: 'List Dist Directory'
        run: ls -l dist

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Osprey-${{ env.VERSION }}-chrome
          path: dist/Osprey-${{ env.VERSION }}-chrome.zip
