name: 'Compile for Edge'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Extract Version'
        id: get_version
        run: |
          VERSION=$(jq -r '.version' src/main/manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 'Print Version'
        run: |
          echo "Extracted version: $VERSION"

      - name: 'Remove update_url from manifest.json'
        run: |
          jq 'del(.update_url)' src/main/manifest.json > src/main/manifest_edge.json

      - name: 'Compile and Zip'
        run: |
          mkdir -p dist
          cp src/main/manifest_edge.json src/main/manifest.json
          zip -r dist/Osprey-$VERSION-edge.zip src/main

      - name: 'List Dist Directory'
        run: ls -l dist

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Osprey-${{ env.VERSION }}-edge
          path: dist/Osprey-${{ env.VERSION }}-edge.zip
